---
area/github:
  - ".github/**/*"

area/pre-commit:
  - ".pre-commit-config.yaml"
  - ".hooks/**/*"

area/mage:
  - "magefiles/*"

area/asdf:
  - ".tool-versions"
  - ".asdf"

area/persistence:
  - "persistence/*"
