---
# Area
- name: area/github
  color: "72ccf3"
  description: >-
    Changes made to GitHub actions
- name: area/pre-commit
  color: "BC9BE3"
  description: >-
    Changes made to pre-commit hooks
- name: area/mage
  color: "7BD7E0"
  description: >-
    Changes made to mage
- name: area/persistence
  color: "#c5def5"
  description: >-
    TTPs simulating persistence mechanisms.
# Renovate
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"
# Semantic Type
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
- name: type/break
  color: "F6412D"
# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: enhancement
  color: "84b6eb"
- name: question
  description: >-
    Clarification and/or additional information required to move forward
  color: "cc317c"
